# Generated by Django 2.1 on 2018-10-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=250, unique=True)),
                ('post_slug', models.SlugField()),
                ('post_body', models.TextField()),
                ('post_thumb', models.ImageField(blank=True, default='default.png', null=True, upload_to='post/')),
                ('post_featured', models.BooleanField(default=False)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250, unique=True)),
                ('cat_slug', models.SlugField()),
                ('cat_description', models.TextField()),
                ('cat_thumb', models.ImageField(blank=True, default='default.png', upload_to='postcat/')),
            ],
            options={
                'verbose_name': 'postcat',
                'verbose_name_plural': 'postcats',
                'ordering': ('cat_name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.PostCat'),
        ),
    ]
