# Generated by Django 2.1 on 2018-10-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, unique=True)),
                ('article_slug', models.SlugField()),
                ('article_body', models.TextField()),
                ('article_thumb', models.ImageField(blank=True, default='default.png', null=True, upload_to='article/')),
                ('article_featured', models.BooleanField(default=False)),
                ('article_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250, unique=True)),
                ('cat_slug', models.SlugField()),
                ('cat_description', models.TextField()),
                ('cat_thumb', models.ImageField(blank=True, default='default.png', upload_to='articlescat/')),
            ],
            options={
                'verbose_name': 'articlecat',
                'verbose_name_plural': 'articlecats',
                'ordering': ('cat_name',),
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_cat',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostCat',
        ),
        migrations.AddField(
            model_name='article',
            name='article_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleCat'),
        ),
    ]
